/**
 * datasetState.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Real dataset values extracted from twinergy_dataset_v3_noisy.csv
 * Reference day: Monday 6 October 2025 (Academic Week 6, Fall Semester)
 * 3 rooms × 24h × 5-min intervals → 864 rows → aggregated for dashboard use
 *
 * Usage:
 *   import { DATASET_SENSOR_STATE, DATASET_CAMPUS_KPIS,
 *            DATASET_HOURLY, DATASET_WEEKLY } from './datasetState';
 *
 * Replace MOCK_SENSOR_STATE with DATASET_SENSOR_STATE everywhere to show
 * real simulated data. The shape is identical to sensorState.js FALLBACK_STATE.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ── Sensor state (compatible with useLiveSensorState shape) ──────────────────
export const DATASET_SENSOR_STATE = {
  "Classroom_1": {
    "status": "optimal",
    "power_w": 9557.2,
    "total_power_kw": 9.56,
    "occupancy": 18,
    "max_occupancy": 30,
    "occupancy_rate": 0.6,
    "temperature_c": null,
    "co2_ppm": 489.0,
    "lux": null,
    "motion": true,
    "lights": false,
    "hvac_active": false,
    "hvac_power_kw": 6.65,
    "outdoor_temp_c": 34.72,
    "scenario": "UC-A",
    "is_unscheduled": 0,
    "is_common_hour": 0,
    "model_confidence": 0.89,
    "recommended": "MAINTAIN",
    "energy_kwh_today": 82.39,
    "waste_kwh_today": 12.4,
    "node": 1
  },
  "Classroom_2": {
    "status": "optimal",
    "power_w": 9691.5,
    "total_power_kw": 9.69,
    "occupancy": 17,
    "max_occupancy": 30,
    "occupancy_rate": 0.57,
    "temperature_c": null,
    "co2_ppm": 480.0,
    "lux": 1022.6,
    "motion": false,
    "lights": false,
    "hvac_active": false,
    "hvac_power_kw": 6.64,
    "outdoor_temp_c": 35.48,
    "scenario": "UC-A",
    "is_unscheduled": 0,
    "is_common_hour": 0,
    "model_confidence": 0.98,
    "recommended": "MAINTAIN",
    "energy_kwh_today": 58.09,
    "waste_kwh_today": 6.44,
    "node": 2
  },
  "Large_Lecture_Hall": {
    "status": "warning",
    "power_w": 15365.9,
    "total_power_kw": 15.37,
    "occupancy": 63,
    "max_occupancy": 75,
    "occupancy_rate": 0.84,
    "temperature_c": 30.08,
    "co2_ppm": 668.0,
    "lux": null,
    "motion": true,
    "lights": false,
    "hvac_active": false,
    "hvac_power_kw": 11.19,
    "outdoor_temp_c": 34.83,
    "scenario": "UC-A",
    "is_unscheduled": 0,
    "is_common_hour": 0,
    "model_confidence": 0.93,
    "recommended": "MAINTAIN",
    "energy_kwh_today": 71.42,
    "waste_kwh_today": 7.25,
    "node": 3
  }
};

// ── Campus-level KPIs (reference day) ────────────────────────────────────────
export const DATASET_CAMPUS_KPIS = {
  "total_energy_kwh": 211.9,
  "total_waste_kwh": 26.09,
  "waste_pct": 12.3,
  "total_power_kw": 8.83,
  "max_occupancy": 124,
  "total_capacity": 135,
  "outdoor_temp_c": 34.0,
  "unscheduled_events": 29,
  "anomaly_flags": 263,
  "date": "2025-10-06",
  "day_label": "Monday 6 Oct 2025 (Academic Week 6)"
};

// ── Hourly data per room (for Analytics charts) ───────────────────────────────
// Each entry: { hour, occupancy, co2, temp, power_kw, lux, pir,
//               energy_kwh, is_common, is_unsched, scenario, confidence }
export const DATASET_HOURLY = {
  "classroom-1": [
    {
      "hour": "00:00",
      "hour_num": 0,
      "occupancy": 0.67,
      "occupancy_rate": 0.02,
      "co2": 416.0,
      "temp": null,
      "power_kw": 0.39,
      "power_w": 393.31,
      "lux": null,
      "pir": 0.17,
      "energy_kwh": 0.39,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.2
    },
    {
      "hour": "01:00",
      "hour_num": 1,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 415.92,
      "temp": null,
      "power_kw": 0.12,
      "power_w": 120.73,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.12,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.12
    },
    {
      "hour": "02:00",
      "hour_num": 2,
      "occupancy": 0.25,
      "occupancy_rate": 0.01,
      "co2": 431.5,
      "temp": null,
      "power_kw": 0.41,
      "power_w": 413.57,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.41,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.22
    },
    {
      "hour": "03:00",
      "hour_num": 3,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 426.25,
      "temp": null,
      "power_kw": 0.31,
      "power_w": 314.18,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.31,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.31
    },
    {
      "hour": "04:00",
      "hour_num": 4,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 425.33,
      "temp": null,
      "power_kw": 0.49,
      "power_w": 489.86,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.49,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.91,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.49
    },
    {
      "hour": "05:00",
      "hour_num": 5,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 423.33,
      "temp": null,
      "power_kw": 0.78,
      "power_w": 777.58,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.78,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.78
    },
    {
      "hour": "06:00",
      "hour_num": 6,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 426.5,
      "temp": null,
      "power_kw": 0.59,
      "power_w": 593.46,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.59,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.59
    },
    {
      "hour": "07:00",
      "hour_num": 7,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 421.25,
      "temp": null,
      "power_kw": 0.58,
      "power_w": 577.34,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.58,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.58
    },
    {
      "hour": "08:00",
      "hour_num": 8,
      "occupancy": 0.58,
      "occupancy_rate": 0.02,
      "co2": 430.83,
      "temp": null,
      "power_kw": 0.47,
      "power_w": 471.8,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.47,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.27
    },
    {
      "hour": "09:00",
      "hour_num": 9,
      "occupancy": 19.33,
      "occupancy_rate": 0.64,
      "co2": 638.33,
      "temp": null,
      "power_kw": 9.37,
      "power_w": 9372.95,
      "lux": null,
      "pir": 0.92,
      "energy_kwh": 9.37,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.9,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.59
    },
    {
      "hour": "10:00",
      "hour_num": 10,
      "occupancy": 12.67,
      "occupancy_rate": 0.42,
      "co2": 612.5,
      "temp": null,
      "power_kw": 7.86,
      "power_w": 7856.42,
      "lux": null,
      "pir": 0.67,
      "energy_kwh": 7.86,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.88,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 2.46
    },
    {
      "hour": "11:00",
      "hour_num": 11,
      "occupancy": 18.5,
      "occupancy_rate": 0.62,
      "co2": 653.33,
      "temp": null,
      "power_kw": 8.77,
      "power_w": 8767.87,
      "lux": null,
      "pir": 0.75,
      "energy_kwh": 8.77,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.89,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.61
    },
    {
      "hour": "12:00",
      "hour_num": 12,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 503.33,
      "temp": null,
      "power_kw": 0.41,
      "power_w": 408.42,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.41,
      "is_common": 1,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.41
    },
    {
      "hour": "13:00",
      "hour_num": 13,
      "occupancy": 15.33,
      "occupancy_rate": 0.51,
      "co2": 596.83,
      "temp": null,
      "power_kw": 8.19,
      "power_w": 8188.26,
      "lux": null,
      "pir": 0.83,
      "energy_kwh": 8.19,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.9,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.52
    },
    {
      "hour": "14:00",
      "hour_num": 14,
      "occupancy": 16.67,
      "occupancy_rate": 0.56,
      "co2": 656.83,
      "temp": null,
      "power_kw": 8.46,
      "power_w": 8455.82,
      "lux": null,
      "pir": 0.83,
      "energy_kwh": 8.46,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.91,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.11
    },
    {
      "hour": "15:00",
      "hour_num": 15,
      "occupancy": 13.33,
      "occupancy_rate": 0.44,
      "co2": 636.08,
      "temp": null,
      "power_kw": 7.82,
      "power_w": 7823.91,
      "lux": null,
      "pir": 0.83,
      "energy_kwh": 7.82,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.91,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.49
    },
    {
      "hour": "16:00",
      "hour_num": 16,
      "occupancy": 4.33,
      "occupancy_rate": 0.14,
      "co2": 515.92,
      "temp": null,
      "power_kw": 2.95,
      "power_w": 2949.89,
      "lux": null,
      "pir": 0.33,
      "energy_kwh": 2.95,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.39
    },
    {
      "hour": "17:00",
      "hour_num": 17,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 419.67,
      "temp": null,
      "power_kw": 0.29,
      "power_w": 286.47,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.29,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.29
    },
    {
      "hour": "18:00",
      "hour_num": 18,
      "occupancy": 10.83,
      "occupancy_rate": 0.36,
      "co2": 534.17,
      "temp": null,
      "power_kw": 8.33,
      "power_w": 8326.38,
      "lux": null,
      "pir": 1.0,
      "energy_kwh": 8.33,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-G",
      "confidence": 0.86,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 1.49
    },
    {
      "hour": "19:00",
      "hour_num": 19,
      "occupancy": 10.08,
      "occupancy_rate": 0.34,
      "co2": 561.08,
      "temp": null,
      "power_kw": 8.32,
      "power_w": 8319.83,
      "lux": null,
      "pir": 0.92,
      "energy_kwh": 8.32,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-G",
      "confidence": 0.87,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.99
    },
    {
      "hour": "20:00",
      "hour_num": 20,
      "occupancy": 11.25,
      "occupancy_rate": 0.37,
      "co2": 585.08,
      "temp": null,
      "power_kw": 7.49,
      "power_w": 7485.91,
      "lux": null,
      "pir": 0.83,
      "energy_kwh": 7.49,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-G",
      "confidence": 0.91,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.49
    },
    {
      "hour": "21:00",
      "hour_num": 21,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 453.75,
      "temp": null,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.95,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    },
    {
      "hour": "22:00",
      "hour_num": 22,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 424.42,
      "temp": null,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.96,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    },
    {
      "hour": "23:00",
      "hour_num": 23,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 427.92,
      "temp": null,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.95,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    }
  ],
  "classroom-2": [
    {
      "hour": "00:00",
      "hour_num": 0,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 424.25,
      "temp": null,
      "power_kw": 0.4,
      "power_w": 397.61,
      "lux": 41.36,
      "pir": null,
      "energy_kwh": 0.4,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.4
    },
    {
      "hour": "01:00",
      "hour_num": 1,
      "occupancy": 1.08,
      "occupancy_rate": 0.04,
      "co2": 432.33,
      "temp": null,
      "power_kw": 0.5,
      "power_w": 498.77,
      "lux": 175.52,
      "pir": null,
      "energy_kwh": 0.5,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.89,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.1
    },
    {
      "hour": "02:00",
      "hour_num": 2,
      "occupancy": 1.08,
      "occupancy_rate": 0.04,
      "co2": 431.42,
      "temp": null,
      "power_kw": 1.08,
      "power_w": 1083.2,
      "lux": 289.24,
      "pir": null,
      "energy_kwh": 1.08,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-C",
      "confidence": 0.87,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.5
    },
    {
      "hour": "03:00",
      "hour_num": 3,
      "occupancy": 0.08,
      "occupancy_rate": 0.0,
      "co2": 424.25,
      "temp": null,
      "power_kw": 0.31,
      "power_w": 314.43,
      "lux": 119.97,
      "pir": null,
      "energy_kwh": 0.31,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.12
    },
    {
      "hour": "04:00",
      "hour_num": 4,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 409.17,
      "temp": null,
      "power_kw": 0.25,
      "power_w": 245.06,
      "lux": 46.54,
      "pir": null,
      "energy_kwh": 0.25,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.25
    },
    {
      "hour": "05:00",
      "hour_num": 5,
      "occupancy": 0.67,
      "occupancy_rate": 0.02,
      "co2": 428.42,
      "temp": null,
      "power_kw": 0.53,
      "power_w": 529.65,
      "lux": 127.03,
      "pir": null,
      "energy_kwh": 0.53,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.33
    },
    {
      "hour": "06:00",
      "hour_num": 6,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 435.33,
      "temp": null,
      "power_kw": 0.4,
      "power_w": 403.5,
      "lux": 63.34,
      "pir": null,
      "energy_kwh": 0.4,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.4
    },
    {
      "hour": "07:00",
      "hour_num": 7,
      "occupancy": 0.58,
      "occupancy_rate": 0.02,
      "co2": 437.33,
      "temp": null,
      "power_kw": 0.7,
      "power_w": 696.99,
      "lux": 214.81,
      "pir": null,
      "energy_kwh": 0.7,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-C",
      "confidence": 0.86,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.32
    },
    {
      "hour": "08:00",
      "hour_num": 8,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 416.0,
      "temp": null,
      "power_kw": 0.11,
      "power_w": 112.82,
      "lux": 46.84,
      "pir": null,
      "energy_kwh": 0.11,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.89,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.11
    },
    {
      "hour": "09:00",
      "hour_num": 9,
      "occupancy": 19.33,
      "occupancy_rate": 0.64,
      "co2": 621.92,
      "temp": null,
      "power_kw": 9.39,
      "power_w": 9388.68,
      "lux": 980.31,
      "pir": null,
      "energy_kwh": 9.39,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.91,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.49
    },
    {
      "hour": "10:00",
      "hour_num": 10,
      "occupancy": 19.83,
      "occupancy_rate": 0.66,
      "co2": 680.75,
      "temp": null,
      "power_kw": 9.71,
      "power_w": 9707.77,
      "lux": 936.26,
      "pir": null,
      "energy_kwh": 9.71,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.92,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.11
    },
    {
      "hour": "11:00",
      "hour_num": 11,
      "occupancy": 10.25,
      "occupancy_rate": 0.34,
      "co2": 604.08,
      "temp": null,
      "power_kw": 7.4,
      "power_w": 7403.94,
      "lux": 739.02,
      "pir": null,
      "energy_kwh": 7.4,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.87,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 1.09
    },
    {
      "hour": "12:00",
      "hour_num": 12,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 454.83,
      "temp": null,
      "power_kw": 0.28,
      "power_w": 283.34,
      "lux": 44.71,
      "pir": null,
      "energy_kwh": 0.28,
      "is_common": 1,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.91,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.28
    },
    {
      "hour": "13:00",
      "hour_num": 13,
      "occupancy": 11.92,
      "occupancy_rate": 0.4,
      "co2": 544.33,
      "temp": null,
      "power_kw": 7.82,
      "power_w": 7822.6,
      "lux": 919.73,
      "pir": null,
      "energy_kwh": 7.82,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.9,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.11
    },
    {
      "hour": "14:00",
      "hour_num": 14,
      "occupancy": 15.25,
      "occupancy_rate": 0.51,
      "co2": 629.67,
      "temp": null,
      "power_kw": 8.27,
      "power_w": 8274.04,
      "lux": 830.19,
      "pir": null,
      "energy_kwh": 8.27,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.93,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.01
    },
    {
      "hour": "15:00",
      "hour_num": 15,
      "occupancy": 3.5,
      "occupancy_rate": 0.12,
      "co2": 512.08,
      "temp": null,
      "power_kw": 2.04,
      "power_w": 2036.12,
      "lux": 369.43,
      "pir": null,
      "energy_kwh": 2.04,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.91,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.25
    },
    {
      "hour": "16:00",
      "hour_num": 16,
      "occupancy": 6.67,
      "occupancy_rate": 0.22,
      "co2": 484.08,
      "temp": null,
      "power_kw": 5.21,
      "power_w": 5214.64,
      "lux": 555.88,
      "pir": null,
      "energy_kwh": 5.21,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.87,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.6
    },
    {
      "hour": "17:00",
      "hour_num": 17,
      "occupancy": 3.5,
      "occupancy_rate": 0.12,
      "co2": 502.5,
      "temp": null,
      "power_kw": 3.0,
      "power_w": 3000.56,
      "lux": 410.51,
      "pir": null,
      "energy_kwh": 3.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.91,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.7
    },
    {
      "hour": "18:00",
      "hour_num": 18,
      "occupancy": 0.92,
      "occupancy_rate": 0.03,
      "co2": 426.17,
      "temp": null,
      "power_kw": 0.44,
      "power_w": 444.37,
      "lux": 275.54,
      "pir": null,
      "energy_kwh": 0.44,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.92,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.05
    },
    {
      "hour": "19:00",
      "hour_num": 19,
      "occupancy": 0.08,
      "occupancy_rate": 0.0,
      "co2": 418.75,
      "temp": null,
      "power_kw": 0.06,
      "power_w": 55.21,
      "lux": 150.65,
      "pir": null,
      "energy_kwh": 0.06,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.95,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.06
    },
    {
      "hour": "20:00",
      "hour_num": 20,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 411.83,
      "temp": null,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": 67.17,
      "pir": null,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.96,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    },
    {
      "hour": "21:00",
      "hour_num": 21,
      "occupancy": 0.17,
      "occupancy_rate": 0.01,
      "co2": 416.25,
      "temp": null,
      "power_kw": 0.11,
      "power_w": 114.59,
      "lux": 225.87,
      "pir": null,
      "energy_kwh": 0.11,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.96,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.11
    },
    {
      "hour": "22:00",
      "hour_num": 22,
      "occupancy": 0.08,
      "occupancy_rate": 0.0,
      "co2": 442.83,
      "temp": null,
      "power_kw": 0.06,
      "power_w": 61.36,
      "lux": 118.22,
      "pir": null,
      "energy_kwh": 0.06,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.95,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.06
    },
    {
      "hour": "23:00",
      "hour_num": 23,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 421.33,
      "temp": null,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": 50.95,
      "pir": null,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.95,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    }
  ],
  "lecture-hall": [
    {
      "hour": "00:00",
      "hour_num": 0,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 418.25,
      "temp": 23.84,
      "power_kw": 0.89,
      "power_w": 891.26,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.89,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.86,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.89
    },
    {
      "hour": "01:00",
      "hour_num": 1,
      "occupancy": 0.08,
      "occupancy_rate": 0.0,
      "co2": 422.58,
      "temp": 23.68,
      "power_kw": 0.6,
      "power_w": 601.77,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.6,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-C",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.32
    },
    {
      "hour": "02:00",
      "hour_num": 2,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 416.0,
      "temp": 23.76,
      "power_kw": 0.01,
      "power_w": 5.39,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.01,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.94,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.01
    },
    {
      "hour": "03:00",
      "hour_num": 3,
      "occupancy": 0.08,
      "occupancy_rate": 0.0,
      "co2": 421.42,
      "temp": 24.03,
      "power_kw": 0.42,
      "power_w": 417.86,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.42,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.92,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.14
    },
    {
      "hour": "04:00",
      "hour_num": 4,
      "occupancy": 0.5,
      "occupancy_rate": 0.01,
      "co2": 436.5,
      "temp": 24.05,
      "power_kw": 0.75,
      "power_w": 750.4,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.75,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.47
    },
    {
      "hour": "05:00",
      "hour_num": 5,
      "occupancy": 0.25,
      "occupancy_rate": 0.0,
      "co2": 431.0,
      "temp": 24.19,
      "power_kw": 0.6,
      "power_w": 602.46,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.6,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.89,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.32
    },
    {
      "hour": "06:00",
      "hour_num": 6,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 407.5,
      "temp": 24.56,
      "power_kw": 0.17,
      "power_w": 164.98,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.16,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.92,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.16
    },
    {
      "hour": "07:00",
      "hour_num": 7,
      "occupancy": 0.75,
      "occupancy_rate": 0.01,
      "co2": 422.33,
      "temp": 24.86,
      "power_kw": 0.66,
      "power_w": 657.41,
      "lux": null,
      "pir": 0.33,
      "energy_kwh": 0.66,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.91,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.09
    },
    {
      "hour": "08:00",
      "hour_num": 8,
      "occupancy": 1.17,
      "occupancy_rate": 0.02,
      "co2": 428.42,
      "temp": 24.65,
      "power_kw": 0.73,
      "power_w": 732.93,
      "lux": null,
      "pir": 0.25,
      "energy_kwh": 0.73,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.89,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.17
    },
    {
      "hour": "09:00",
      "hour_num": 9,
      "occupancy": 50.67,
      "occupancy_rate": 0.68,
      "co2": 1004.83,
      "temp": 29.76,
      "power_kw": 13.53,
      "power_w": 13534.62,
      "lux": null,
      "pir": 0.92,
      "energy_kwh": 13.53,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.91,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.72
    },
    {
      "hour": "10:00",
      "hour_num": 10,
      "occupancy": 37.33,
      "occupancy_rate": 0.5,
      "co2": 974.92,
      "temp": 28.89,
      "power_kw": 12.3,
      "power_w": 12301.53,
      "lux": null,
      "pir": 0.92,
      "energy_kwh": 12.3,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.89,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 1.48
    },
    {
      "hour": "11:00",
      "hour_num": 11,
      "occupancy": 30.83,
      "occupancy_rate": 0.41,
      "co2": 855.58,
      "temp": 28.69,
      "power_kw": 11.17,
      "power_w": 11166.8,
      "lux": null,
      "pir": 0.83,
      "energy_kwh": 11.17,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.9,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.9
    },
    {
      "hour": "12:00",
      "hour_num": 12,
      "occupancy": 63.42,
      "occupancy_rate": 0.85,
      "co2": 1203.17,
      "temp": 31.14,
      "power_kw": 14.85,
      "power_w": 14854.6,
      "lux": null,
      "pir": 1.0,
      "energy_kwh": 14.85,
      "is_common": 1,
      "is_unsched": 0,
      "scenario": "UC-B",
      "confidence": 0.87,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.0
    },
    {
      "hour": "13:00",
      "hour_num": 13,
      "occupancy": 24.75,
      "occupancy_rate": 0.33,
      "co2": 903.5,
      "temp": 28.39,
      "power_kw": 10.68,
      "power_w": 10678.02,
      "lux": null,
      "pir": 0.83,
      "energy_kwh": 10.68,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-A",
      "confidence": 0.92,
      "hvac": "COOLING",
      "lighting": "FULL",
      "waste_kwh": 0.0
    },
    {
      "hour": "14:00",
      "hour_num": 14,
      "occupancy": 2.67,
      "occupancy_rate": 0.04,
      "co2": 560.92,
      "temp": 26.46,
      "power_kw": 1.77,
      "power_w": 1768.98,
      "lux": null,
      "pir": 0.17,
      "energy_kwh": 1.77,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.9,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.42
    },
    {
      "hour": "15:00",
      "hour_num": 15,
      "occupancy": 0.17,
      "occupancy_rate": 0.0,
      "co2": 429.5,
      "temp": 26.22,
      "power_kw": 0.42,
      "power_w": 420.78,
      "lux": null,
      "pir": 0.25,
      "energy_kwh": 0.42,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.91,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.14
    },
    {
      "hour": "16:00",
      "hour_num": 16,
      "occupancy": 0.5,
      "occupancy_rate": 0.01,
      "co2": 420.08,
      "temp": 26.05,
      "power_kw": 1.05,
      "power_w": 1045.36,
      "lux": null,
      "pir": 0.17,
      "energy_kwh": 1.05,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.88,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.48
    },
    {
      "hour": "17:00",
      "hour_num": 17,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 410.0,
      "temp": 25.86,
      "power_kw": 0.29,
      "power_w": 290.76,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.29,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-C",
      "confidence": 0.92,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.29
    },
    {
      "hour": "18:00",
      "hour_num": 18,
      "occupancy": 0.08,
      "occupancy_rate": 0.0,
      "co2": 416.83,
      "temp": 25.71,
      "power_kw": 0.08,
      "power_w": 83.11,
      "lux": null,
      "pir": 0.08,
      "energy_kwh": 0.08,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.95,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.08
    },
    {
      "hour": "19:00",
      "hour_num": 19,
      "occupancy": 0.25,
      "occupancy_rate": 0.0,
      "co2": 410.33,
      "temp": 25.26,
      "power_kw": 0.08,
      "power_w": 83.6,
      "lux": null,
      "pir": 0.17,
      "energy_kwh": 0.08,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.94,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.08
    },
    {
      "hour": "20:00",
      "hour_num": 20,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 406.33,
      "temp": 24.93,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.97,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    },
    {
      "hour": "21:00",
      "hour_num": 21,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 417.75,
      "temp": 24.81,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.96,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    },
    {
      "hour": "22:00",
      "hour_num": 22,
      "occupancy": 0.5,
      "occupancy_rate": 0.01,
      "co2": 429.5,
      "temp": 24.23,
      "power_kw": 0.36,
      "power_w": 364.26,
      "lux": null,
      "pir": 0.17,
      "energy_kwh": 0.36,
      "is_common": 0,
      "is_unsched": 1,
      "scenario": "UC-D",
      "confidence": 0.94,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.09
    },
    {
      "hour": "23:00",
      "hour_num": 23,
      "occupancy": 0.0,
      "occupancy_rate": 0.0,
      "co2": 424.08,
      "temp": 24.15,
      "power_kw": 0.0,
      "power_w": 0.0,
      "lux": null,
      "pir": 0.0,
      "energy_kwh": 0.0,
      "is_common": 0,
      "is_unsched": 0,
      "scenario": "UC-D",
      "confidence": 0.94,
      "hvac": "OFF",
      "lighting": "OFF",
      "waste_kwh": 0.0
    }
  ]
};

// ── Weekly energy (Mon–Fri, week of Oct 6) ────────────────────────────────────
export const DATASET_WEEKLY = {
  "classroom-1": [
    {
      "date": "2025-10-06",
      "energy_kwh": 82.39
    },
    {
      "date": "2025-10-07",
      "energy_kwh": 67.37
    },
    {
      "date": "2025-10-08",
      "energy_kwh": 82.23
    },
    {
      "date": "2025-10-09",
      "energy_kwh": 68.35
    },
    {
      "date": "2025-10-10",
      "energy_kwh": 31.95
    }
  ],
  "classroom-2": [
    {
      "date": "2025-10-06",
      "energy_kwh": 58.09
    },
    {
      "date": "2025-10-07",
      "energy_kwh": 69.91
    },
    {
      "date": "2025-10-08",
      "energy_kwh": 58.27
    },
    {
      "date": "2025-10-09",
      "energy_kwh": 68.9
    },
    {
      "date": "2025-10-10",
      "energy_kwh": 31.38
    }
  ],
  "lecture-hall": [
    {
      "date": "2025-10-06",
      "energy_kwh": 71.42
    },
    {
      "date": "2025-10-07",
      "energy_kwh": 62.73
    },
    {
      "date": "2025-10-08",
      "energy_kwh": 72.57
    },
    {
      "date": "2025-10-09",
      "energy_kwh": 93.74
    },
    {
      "date": "2025-10-10",
      "energy_kwh": 43.04
    }
  ]
};

// ── Scenario labels (for legend) ─────────────────────────────────────────────
export const SCENARIO_LABELS = {
  'UC-A': { label: 'Scheduled Class',          color: '#2563eb' },
  'UC-B': { label: 'Common Hour Spike',         color: '#ef4444' },
  'UC-C': { label: 'Energy Waste (Empty+On)',   color: '#f59e0b' },
  'UC-D': { label: 'Shutdown / Closed',         color: '#64748b' },
  'UC-E': { label: 'Scheduled but Empty',       color: '#8b5cf6' },
  'UC-F': { label: 'Unscheduled Small Group',   color: '#10b981' },
  'UC-G': { label: 'Other',                     color: '#94a3b8' },
};

// ── Helper: get sensor state for a specific room ──────────────────────────────
export function getRoomState(roomId) {
  return DATASET_SENSOR_STATE[roomId] ?? null;
}

// ── Helper: get hourly data for analytics charts ──────────────────────────────
export function getHourlyForRoom(roomId) {
  // Map Firebase keys → dataset keys
  const keyMap = {
    'Classroom_1':        'classroom-1',
    'Classroom_2':        'classroom-2',
    'Large_Lecture_Hall': 'lecture-hall',
  };
  return DATASET_HOURLY[keyMap[roomId] ?? roomId] ?? [];
}

// ── Helper: compute total campus power from dataset ───────────────────────────
export function computeDatasetKPIs() {
  const rooms = Object.values(DATASET_SENSOR_STATE);
  const totalPower_w  = rooms.reduce((s, r) => s + (r.power_w ?? 0), 0);
  const totalOcc      = rooms.reduce((s, r) => s + (r.occupancy ?? 0), 0);
  const maxOcc        = rooms.reduce((s, r) => s + (r.max_occupancy ?? 0), 0);
  return {
    totalPower_w,
    totalPower_kw:  (totalPower_w / 1000).toFixed(2),
    totalOccupancy: totalOcc,
    maxOccupancy:   maxOcc,
    occupancyPct:   Math.round((totalOcc / maxOcc) * 100),
    criticalRooms:  rooms.filter(r => r.status === 'critical').length,
    warningRooms:   rooms.filter(r => r.status === 'warning').length,
    anyFire:        false,
    energyToday_kwh: DATASET_CAMPUS_KPIS.total_energy_kwh,
    wasteToday_kwh:  DATASET_CAMPUS_KPIS.total_waste_kwh,
    wastePct:        DATASET_CAMPUS_KPIS.waste_pct,
  };
}